<template>
  <CCard>
    <CCardBody>
      <CRow>
        <CCol md="12">
          <template>
            <table style="width: 100%">
              <thead>
                <th style="text-align: center; width: 20%">Type</th>
                <th style="text-align: center; width: 7%">ID 1</th>
                <th style="text-align: center; width: 13%">ID 2</th>
                <th style="text-align: center; width: 10%">ID 3</th>
                <th style="text-align:centerwidth:5%">ID 4</th>
                <th style="text-align: center; width: 8%">
                  SN Prefix (static)
                </th>
                <th style="text-align: center; width: 8%">
                  SN Length (dynamic)
                </th>
                <th style="text-align: center; width: 13%">Generate Type</th>
                <th style="text-align: center; width: 15%">Charset</th>
              </thead>
              <tbody
                :v-if="total_pid > 0"
                v-for="index in total_pid"
                :key="index"
              >
                <tr>
                  <td>
                    <br />
                    <CSelect
                      :label="title[index - 1]"
                      horizontal
                      :disabled="readonly"
                      :options="list_epc_type"
                      @change="handleChangePid(index - 1)"
                      :value.sync="result[index - 1].epc_type"
                      placeholder="--Select--"
                      :is-valid="!error[index - 1].epc_type"
                    >
                    </CSelect>
                  </td>
                  <td>
                    <br />
                    <CInput
                      v-c-tooltip="
                        'This ID1 will be in the first order of the Epc Hr arrangement which will be generated by mertrack, the character length is only 1 digit number.'
                      "
                      :disabled="readonly"
                      v-model="result[index - 1].id1"
                      @keyup="handleChangePid(index - 1)"
                      @keypress="
                        validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: digit_max[index - 1].id1,
                          name: 'id1',
                          type: 'number',
                        })
                      "
                      :is-valid="!error[index - 1].id1"
                    />
                  </td>
                  <td>
                    <br />
                    <CInput
                      v-c-tooltip="
                        'ID2 is filled with a company prefix with a minimum length of 6 digits and a maximum length of 9 digits.'
                      "
                      :disabled="readonly || packaging_level != 1"
                      v-model="result[index - 1].id2"
                      @keyup="handleChangePid(index - 1)"
                      @keypress="
                        validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: digit_max[index - 1].id2,
                          name: 'id2',
                          type: 'number',
                        })
                      "
                      :is-valid="!error[index - 1].id2"
                    />
                  </td>
                  <td>
                    <br />
                    <CInput
                      v-c-tooltip="
                        'ID3 is filled with the remaining 13 digits if ID1, ID2 and ID3 are added together.'
                      "
                      :disabled="
                        readonly ||
                        digit_max[index - 1].id3 == 0 ||
                        packaging_level != 1
                      "
                      :readonly="result[index - 1].epc_type === 'sscc'"
                      v-model="result[index - 1].id3"
                      @keyup="handleChangePid(index - 1)"
                      @keypress="
                        validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: digit_max[index - 1].id3,
                          name: 'id3',
                          type: 'number',
                        })
                      "
                      :is-valid="result[index - 1].id3 && !error[index - 1].id3"
                    />
                  </td>
                  <td>
                    <br />
                    <CInput
                      :disabled="readonly"
                      readonly
                      v-model="result[index - 1].id4"
                      @keyup="handleChangePid(index - 1)"
                      @keypress="
                        validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: digit_max[index - 1].id4,
                          name: 'id4',
                          type: 'number',
                        })
                      "
                      :is-valid="result[index - 1].id4 && !error[index - 1].id4"
                    />
                  </td>
                  <td>
                    <br />
                    <CInput
                      :disabled="readonly"
                      v-model="result[index - 1].sn_prefix"
                      @keyup="handleChangePid(index - 1)"
                      @keypress="
                        validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: digit_max[index - 1].sn_prefix,
                          name: 'sn_prefix',
                          type:
                            result[index - 1].sn_charset == 'alphanumeric'
                              ? 'string'
                              : 'number',
                        })
                      "
                      :is-valid="
                        result[index - 1].sn_prefix &&
                        !error[index - 1].sn_prefix
                      "
                    />
                  </td>
                  <td>
                    <br />
                    <CInput
                      :disabled="readonly"
                      :readonly="result[index - 1].epc_type === 'sscc'"
                      v-model="result[index - 1].generated_sn_len"
                      @keyup="handleChangePid(index - 1)"
                      @keypress="
                        validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: 2,
                          name: 'generated_sn_len',
                          type: 'number',
                        })
                      "
                      :is-valid="!error[index - 1].generated_sn_len"
                    />
                    <CInput
                      :hidden="true"
                      :readonly="result[index - 1].epc_type === 'sscc'"
                      v-model="result[index - 1].triger"
                      @keyup="handleChangePid(index - 1)"
                      @keypress="
                        validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: 2,
                          name: 'triger',
                          type: 'number',
                        })
                      "
                    />
                  </td>
                  <td>
                    <br />
                    <CSelect
                      :disabled="readonly"
                      :value.sync="result[index - 1].sn_generate_type"
                      @change="handleChangePid(index - 1)"
                      :options="list_generate_type"
                      placeholder="--Select--"
                      :add-input-classes="{
                        'is-invalid':
                          !result[index - 1].sn_generate_type &&
                          error[index - 1].sn_generate_type,
                      }"
                      :is-valid="
                        result[index - 1].sn_generate_type &&
                        !error[index - 1].generated_sn_len
                      "
                    />
                  </td>
                  <td>
                    <br />
                    <CSelect
                      :disabled="
                        result[index - 1].epc_type === 'sscc' || readonly
                      "
                      @change="handleChangePid(index - 1)"
                      :value.sync="result[index - 1].sn_charset"
                      :options="list_charset"
                      placeholder="--Select--"
                      :is-valid="
                        result[index - 1].sn_charset &&
                        !error[index - 1].sn_charset
                      "
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </template>
        </CCol>
      </CRow>
    </CCardBody>
  </CCard>
</template>

<script>
export default {
  name: "MasterPid",
  props: ["item", "packaging_level", "default_data", "readonly", "ref_data"],
  watch: {
    ref_data: {
      handler(n, o) {
        let idx = 0;
        for (const it of this.result) {
          this.result[`${idx}`].id2 = this.ref_data.id2;
          this.result[`${idx}`].id3 = this.ref_data.id3;
          idx += 1;
        }
      },
      deep: true,
    },
  },
  mounted() {
    if (this.packaging_level) {
      if (this.packaging_level == 1) {
        this.total_pid = 1;
        this.result = [this.initial_value(0)];
      } else if (this.packaging_level != 1) {
        this.total_pid = 2;
        this.result = [this.initial_value(0), this.initial_value(1)];
      }
      if (this.default_data.length > 0) {
        this.result = this.default_data;
      }
      if (this.item) {
        this.product = this.item;
      }
      if (this.result.length == 2 && this.result[1].flag_full == 1)
        this.swapPositions(this.result, 0, 1);
    }
    for (var i = 0; i < this.total_pid; i++) {
      this.validationData(i);
    }
  },
  data() {
    return {
      total_pid: 2,
      title: ["Full", "Partial"],
      digit_sscc: 17, // 1 digit adalah check digit
      digit_sgtin: 13, // 1 digit adalah check digit
      max_digit_ssscc: null,
      max_digit_sgtin: 20,
      digit_max: [this.initial_max(), this.initial_max()],
      max_sn_pref: 2,
      product: {},
      result: [this.initial_value(0), this.initial_value(1)],
      list_charset: [
        { value: "alphanumeric", label: "Alphanumeric" },
        { value: "numeric", label: "Numeric" },
      ],
      list_epc_type: [
        { value: "sscc", label: "SSCC" },
        { value: "sgtin", label: "SGTIN" },
      ],
      list_generate_type: [
        { value: "random", label: "Random" },
        { value: "sequential", label: "Sequential" },
      ],
      error: [this.initial_error(), this.initial_error()],
      have_error: [false, false],
      initial_save: false,
    };
  },
  methods: {
    initial_max(num) {
      let it = {
        id1: 1,
        id2: 12,
        id3: 2,
        id4: 0,
        sn_prefix: num || 2,
      };
      return it;
    },
    initial_error() {
      let it = {
        epc_type: false,
        generated_sn_len: false,
        sn_charset: false,
        sn_generate_type: false,
        id1: false,
        id2: false,
      };
      return it;
    },
    initial_value(num) {
      let it = {
        product_id: this.item.product_id ?? null,
        packaging_level: this.packaging_level ?? null,
        flag_full: num ?? 1,
        flag_serial: this.item.product_type == "1" ? 0 : 1,
        epc_type: "",
        id1: null,
        id2: null,
        id3: null,
        id4: null,
        sn_charset: null,
        sn_generate_type: null,
        sn_prefix: null,
        generated_sn_len: null,
        error: true,
        triger: 1,
      };
      return it;
    },
    swapPositions(array, a, b) {
      [array[a], array[b]] = [array[b], array[a]];
    },
    validateNumber: function ({ event, data, max }) {
      event = event ? event : window.event;
      var charCode = event.which ? event.which : event.keyCode;
      if (data && data.toString().length > max - 1) {
        event.preventDefault();
      } else if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        event.preventDefault();
      } else {
        return true;
      }
    },

    validateCharSet: function ({ event, num, name, max, type }) {
      let data = this.result[num][name];
      event = event ? event : window.event;
      var charCode = event.which ? event.which : event.keyCode;
      if (data && data.toString().length > max - 1) {
        event.preventDefault();
      } else if (!type || type == "number") {
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
          event.preventDefault();
        } else {
          return true;
        }
      } else {
        return true;
      }
    },
    handleChangePid(num) {
      this.error[num] = this.initial_error();
      let epc = this.result[`${num}`].epc_type;
      if (this.ref_data) {
        this.result[`${num}`].id2 = this.ref_data.id2;
        this.result[`${num}`].id3 = this.ref_data.id3;
      }

      if (epc === "sscc") {
        this.checkSSCC(num);
      } else if (epc === "sgtin") {
        this.checkSGTIN(num);
      }
      this.validationData(num);
    },
    checkSSCC(num) {
      this.result[`${num}`].sn_charset = "numeric";
      this.result[`${num}`].id3 = null;
      this.result[`${num}`].generated_sn_len = this.digit_sscc;
      this.result[`${num}`].sn_charset = "numeric";
      let id1 = this.result[`${num}`].id1 ?? "";
      let id2 = this.result[`${num}`].id2 ?? "";
      let sn_prefix = this.result[`${num}`].sn_prefix ?? "";
      let concat = "" + id1 + id2 + sn_prefix;
      this.result[`${num}`].generated_sn_len =
        this.result[`${num}`].generated_sn_len - concat.length;
      // TRIGER
      this.result[num].triger = num + Math.random().toString(16);
      // TRIGER
    },
    checkSGTIN(num) {
      let sn_prefix = this.result[`${num}`].sn_prefix ?? "";
      let concat_sn = ("" + sn_prefix).length;
      let len_sn = parseInt(this.result[`${num}`].generated_sn_len);
      if (concat_sn + len_sn > this.max_digit_sgtin) {
        this.result[`${num}`].generated_sn_len =
          this.max_digit_sgtin - concat_sn;
      }
      let id1 = this.result[`${num}`].id1 ?? "";
      let id2 = this.result[`${num}`].id2 ?? "";
      let id3 = this.result[`${num}`].id3 ?? "";
      let concat = ("" + id1 + id2 + id3).length;
      if (concat != this.digit_sgtin) {
        this.error[`${num}`].id2 = true;
        this.error[`${num}`].id3 = true;
      }
      let concat_1 = ("" + id1 + id2).length;
      let concat_2 = ("" + id1 + id3).length;
      if (concat_1 >= this.digit_sgtin) {
        this.result[`${num}`].id3 = "";
        this.digit_max[num].id3 = 0;
      } else {
        this.digit_max[num].id2 = this.digit_sgtin - concat_2;
        this.digit_max[num].id3 = this.digit_sgtin - concat_1;
      }
      // TRIGER
      this.result[num].triger = num + Math.random().toString(16);
      // TRIGER
    },
    validationData(num) {
      this.result[num].error = false;
      let is_error = false;
      for (var key in this.error[num]) {
        if (!this.result[`${num}`][key]) {
          this.error[num][key] = true;
          is_error = true;
        } else if (
          key == "id2" &&
          this.result[`${num}`][key].toString().length <= 5
        ) {
          this.error[num][key] = true;
          is_error = true;
        } else if (
          key == "generated_sn_len" &&
          this.result[`${num}`][key] <= 0
        ) {
          this.error[num][key] = true;
          is_error = true;
        }
      }
      if (is_error) {
        this.result[num].error = true;
      }
      this.$emit("handleResultPid", this.result);
    },
  },
};
</script>
