<template>
  <CRow>
    <CCol md="12">
      <template class="tableWrapper">
        <table class="tableElement" style="width: 100%; padding: auto">
          <thead>
            <th style="text-align: center; width: 5%"></th>
            <th style="text-align: center; width: 10%">Type</th>
            <th style="text-align: center; width: 12%">ID 1</th>
            <th style="text-align: center; width: 11%">ID 2</th>
            <th style="text-align: center; width: 8%">ID 3</th>
            <!-- <th style="text-align: center; width: 6%">ID 4</th> -->
            <th style="text-align: center; width: 6%">
              <p>SN Prefix (static)</p>
            </th>
            <th style="text-align: center; width: 5%; margin: 0">
              <p>SN Length (dynamic)</p>
            </th>
            <th style="text-align: center; width: 12%">
              <p>Generate Type</p>
            </th>
            <th style="text-align: center; width: 12%">
              <p>Charset</p>
            </th>
            <th style="text-align: center; width: 18%">Layout</th>
            <th style="text-align: center; width: 53%"></th>
          </thead>
          <tbody :v-if="total_pid > 0" v-for="index in total_pid" :key="index">
            <tr>
              <td>
                {{ title[index - 1] }}
              </td>
              <td>
                <br />
                <CSelect
                  block
                  size="sm"
                  :disabled="readonly"
                  :options="
                    packaging_level == 1
                      ? list_epc_type.filter((it) => it.value != 'sscc')
                      : index % 2 == 0
                      ? list_epc_type.filter((it) => it.value != 'sgtin')
                      : list_epc_type
                  "
                  :value.sync="result[index - 1].epc_type"
                  placeholder="--Select--"
                  :is-valid="result[index - 1].epc_type ? true : false"
                  @change="handleChangePid(index - 1)"
                >
                </CSelect>
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  v-c-tooltip="
                    'This ID1 will be in the first order of the Epc Hr arrangement which will be generated by mertrack, the character length is only 1 digit number.'
                  "
                  :disabled="readonly || result[index - 1].epc_type == 'nie'"
                  v-model="result[index - 1].id1"
                  @keypress="
                    result[index - 1].epc_type == 'nie'
                      ? null
                      : validateCharSet({
                          event: $event,
                          num: index - 1,
                          max: digit_max[index - 1].id1,
                          name: 'id1',
                          type: 'number',
                        })
                  "
                  @change="handleChangePid(index - 1)"
                  :is-valid="!error[index - 1].id1"
                />
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  v-c-tooltip="
                    'ID2 is filled with a company prefix with a minimum length of 6 digits and a maximum length of 9 digits.'
                  "
                  :disabled="true"
                  v-model="result[index - 1].id2"
                  :is-valid="!error[index - 1].id2"
                />
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  v-c-tooltip="
                    'ID3 is filled with the remaining 13 digits if ID1, ID2 and ID3 are added together.'
                  "
                  :disabled="true"
                  :readonly="result[index - 1].epc_type === 'sscc'"
                  v-model="result[index - 1].id3"
                  :is-valid="!error[index - 1].id3"
                />
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  :disabled="readonly"
                  v-model="result[index - 1].sn_prefix"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: digit_max[index - 1].sn_prefix,
                      name: 'sn_prefix',
                      type:
                        result[index - 1].sn_charset == 'alphanumeric'
                          ? 'string'
                          : 'number',
                    })
                  "
                  @keyup="handleChangePid(index - 1)"
                  :is-valid="!error[index - 1].sn_prefix"
                />
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  :disabled="readonly"
                  :readonly="result[index - 1].epc_type === 'sscc'"
                  v-model="result[index - 1].generated_sn_len"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: 2,
                      name: 'generated_sn_len',
                      type: 'number',
                    })
                  "
                  @keyup="handleChangePid(index - 1)"
                  :is-valid="result[index - 1].generated_sn_len ? true : false"
                />
              </td>
              <td>
                <br />
                <CSelect
                  size="sm"
                  :disabled="readonly"
                  :value.sync="result[index - 1].sn_generate_type"
                  :options="list_generate_type"
                  placeholder="--Select--"
                  :is-valid="result[index - 1].sn_generate_type ? true : false"
                  @change="handleChangePid(index - 1)"
                />
              </td>
              <td>
                <br />
                <CSelect
                  size="sm"
                  :disabled="result[index - 1].epc_type === 'sscc' || readonly"
                  :value.sync="result[index - 1].sn_charset"
                  :options="list_charset"
                  placeholder="--Select--"
                  :is-valid="result[index - 1].sn_charset ? true : false"
                  @change="handleChangePid(index - 1)"
                />
              </td>
              <td>
                <br />
                <CSelect
                  size="sm"
                  :value.sync="result[index - 1].conf_layout_id"
                  :options="list_layout"
                  placeholder="-"
                  :is-valid="result[index - 1].conf_layout_id ? true : false"
                  @change="handleChangePid(index - 1)"
                />
              </td>
            </tr>
          </tbody>
        </table>
      </template>
    </CCol>
  </CRow>
</template>

<script>
import { getConfLayout } from '../../resource/ConfLayout';
export default {
  name: 'MasterPid',
  props: {
    item: Object,
    packaging_level: Number,
    default_data: Array,
    readonly: Boolean,
    ref_data: Object,
  },
  beforeMount() {
    let have_pid = false;
    var idx = 0;
    if (this.packaging_level == 1) {
      this.total_pid = 1;
      this.result.splice(1, 1);
    }
    if (Object.keys(this.item).length > 5) {
      idx = 0;
      this.item.mst_pid.map((val) => {
        if (val.packaging_level == this.packaging_level) {
          have_pid = true;
          this.result[idx] = val;
          idx += 1;
        }
      });
      if (this.result.length == 2 && this.result[1].flag_full == 1) {
        this.swapPositions(this.result, 0, 1);
      }
    }
    if (!have_pid) {
      idx = 0;
      for (const it of this.result) {
        this.item.mst_pid.push(it);
        idx += 1;
      }
    }
    return;
  },
  watch: {
    result: {
      handler() {
        this.$emit('handleResultPid', this.result);
        // console.log(data);
      },
      deep: true,
    },
    'item.company_prefix': {
      handler() {
        for (var i = 0; i < this.result.length; i++) {
          this.handleChangePid(i);
        }
      },
      deep: true,
    },
    'item.item_reference': {
      handler() {
        for (var i = 0; i < this.result.length; i++) {
          this.handleChangePid(i);
        }
      },
      deep: true,
    },
    'item.nie': {
      handler() {
        for (var i = 0; i < this.result.length; i++) {
          this.handleChangePid(i);
        }
      },
      deep: true,
    },
  },
  mounted() {
    this.loadLayout();
    this.loadEpcType();
  },
  data() {
    return {
      canLooping: true,
      total_pid: 2,
      title: ['Full', 'Partial'],
      digit_sscc: 17, // 1 digit adalah check digit
      digit_sgtin: 13, // 1 digit adalah check digit
      max_digit_ssscc: null,
      max_digit_sgtin: 20,
      digit_max: [this.initial_max(), this.initial_max()],
      max_sn_pref: 2,
      product: {},
      result: [this.initial_value(0), this.initial_value(1)],
      list_charset: [
        { value: 'alphanumeric', label: 'Alphanumeric' },
        { value: 'numeric', label: 'Numeric' },
      ],
      list_layout: [],
      list_epc_type: [],
      only_sscc: [{ value: 'sscc', label: 'SSCC' }],
      only_sgtin: [{ value: 'sgtin', label: 'SGTIN' }],
      list_generate_type: [
        { value: 'random', label: 'Random' },
        { value: 'sequential', label: 'Sequential' },
      ],
      error: [this.initial_error(), this.initial_error()],
      have_error: [false, false],
      initial_save: false,
    };
  },
  computed: {},
  methods: {
    handleChangePid(idx) {
      this.result[idx].error = false;
      let thisData = this.result[idx];
      if (thisData.epc_type === 'nie') {
        this.syncNie(idx);
      } else if (thisData.epc_type === 'sgtin') {
        this.syncSgtin(idx);
      } else if (thisData.epc_type === 'sscc') {
        this.syncSSCC(idx);
      }
    },

    syncSSCC(idx) {
      this.result[idx].id3 = '';
      this.error[idx] = this.initial_error();
      if (
        !this.isNum(this.result[idx].id1) ||
        this.result[idx].id1.length > 1
      ) {
        this.result[idx].id1 = '';
      }
      if (this.item.company_prefix) {
        this.result[idx].id2 = this.item.company_prefix;
      }
      if (!this.item.company_prefix) {
        this.result[idx].error = true;
        this.error[idx].id2 = true;
      }
      if (!this.result[idx].id1) {
        this.result[idx].error = true;
        this.error[idx].id1 = true;
      }
      if (this.result[idx].id2.length > 9) {
        this.result[idx].error = true;
        this.error[idx].id2 = true;
      }
      if (!this.result[idx].generated_sn_len) {
        this.result[idx].generated_sn_len = 7;
      }
      let id1 = 0;
      let id2 = 0;
      let sn_prefix = 0;
      try {
        id1 = this.result[idx].id1.length;
        id2 = this.result[idx].id2.length;
        sn_prefix = this.result[idx].sn_prefix.length;
        this.result[idx].generated_sn_len = 18 - id1 - id2 - sn_prefix;
      } catch (e) {
        console.log(e);
      }
      this.result[idx].sn_charset = 'numeric';
    },
    syncSgtin(idx) {
      this.error[idx] = this.initial_error();
      if (
        !this.isNum(this.result[idx].id1) ||
        this.result[idx].id1.length > 1
      ) {
        this.result[idx].id1 = '';
      }
      if (this.item.company_prefix) {
        this.result[idx].id2 = this.item.company_prefix;
      }
      if (this.item.item_reference) {
        this.result[idx].id3 = this.item.item_reference;
      }
      if (!this.item.company_prefix) {
        this.result[idx].error = true;
        this.error[idx].id2 = true;
      }
      if (!this.item.item_reference) {
        this.result[idx].error = true;
        this.error[idx].id3 = true;
      }
      if (!this.result[idx].id1) {
        this.result[idx].error = true;
        this.error[idx].id1 = true;
      }
      if (this.result[idx].id2.length > 9) {
        this.result[idx].error = true;
        this.error[idx].id2 = true;
      }
      if (this.result[idx].id2.length + this.result[idx].id3.length != 12) {
        this.result[idx].error = true;
        this.error[idx].id2 = true;
        this.error[idx].id3 = true;
      }
      if (!this.result[idx].generated_sn_len) {
        this.result[idx].generated_sn_len = 7;
      }
    },
    syncNie(idx) {
      this.error[idx] = this.initial_error();
      this.result[idx].id1 = '';
      this.result[idx].id2 = '';
      this.result[idx].id3 = '';
      if (this.item.nie && 10 > this.item.nie.length < 16) {
        this.result[idx].id1 = this.item.nie;
      } else {
        this.result[idx].error = true;
        this.error[idx].id1 = true;
      }
      if (!this.result[idx].generated_sn_len) {
        this.result[idx].generated_sn_len = 7;
      }
    },
    loadEpcType() {
      try {
        let data = [];
        for (const it of process.env.VUE_APP_EPC_TYPE.split(',')) {
          data.push({
            value: it,
            label: it.toLocaleUpperCase(),
          });
        }
        this.list_epc_type = data;
      } catch (e) {
        console.log(e);
      }
    },

    async loadLayout() {
      let _res = await getConfLayout({
        status: 'Active',
        packaging_level: this.packaging_level,
      });
      if (_res) {
        this.list_layout = [];
        for (const it of _res.data) {
          it.value = it.id;
          it.label = it.name;
          this.list_layout.push(it);
        }
      }
    },

    initial_max(num) {
      let it = {
        id1: 1,
        id2: 8,
        id3: 2,
        id4: 0,
        sn_prefix: num || 3,
      };
      return it;
    },

    initial_error() {
      let it = {
        epc_type: false,
        generated_sn_len: false,
        sn_charset: false,
        sn_generate_type: false,
        id1: false,
        id2: false,
        conf_layout_id: false,
      };
      return it;
    },

    initial_value(num) {
      let it = {
        product_id: this.item.product_id ?? null,
        packaging_level: this.packaging_level ?? null,
        flag_full: num ?? 1,
        flag_serial: this.item.product_type == '1' ? 0 : 1,
        epc_type: null,
        id1: null,
        id2: null,
        id3: null,
        id4: null,
        sn_charset: null,
        sn_generate_type: null,
        sn_prefix: null,
        generated_sn_len: null,
        conf_layout_id: null,
        error: true,
      };
      return it;
    },

    swapPositions(array, a, b) {
      [array[a], array[b]] = [array[b], array[a]];
    },

    validateNumber: function ({ event, data, max }) {
      event = event ? event : window.event;
      var charCode = event.which ? event.which : event.keyCode;
      if (data && data.toString().length > max - 1) {
        event.preventDefault();
      } else if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        event.preventDefault();
      } else {
        return true;
      }
    },

    validateCharSet: function ({ event, num, name, max, type }) {
      let data = this.result[num][name];
      event = event ? event : window.event;
      var charCode = event.which ? event.which : event.keyCode;
      if (data && data.toString().length > max - 1) {
        event.preventDefault();
      } else if (!type || type == 'number') {
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
          event.preventDefault();
        } else {
          return true;
        }
      } else {
        return true;
      }
    },

    isNum(num) {
      const pattern = /^\d+$/;
      if (pattern.test(num)) return true;
      else return false;
    },
  },
};
</script>
<style>
.is-valid .custom-select-icon,
.is-invalid .custom-select-icon {
  width: 1px;
}
.tableElement {
  margin: 0px auto;
  width: 100%;
}

.tableCell {
  width: 50%;
}

.tableWrapper {
  border: 1px solid red;
  margin: 0px;
  padding: 0 0px;
}
</style>
