<template>
  <CRow>
    <CCol md="12">
      <template>
        <table style="width: 100%">
          <thead>
            <th style="text-align: center; width: 5%"></th>
            <th style="text-align: center; width: 11%">Type</th>
            <th style="text-align: center; width: 6%">ID 1</th>
            <th style="text-align: center; width: 11%">ID 2</th>
            <th style="text-align: center; width: 8%">ID 3</th>
            <th style="text-align: center; width: 6%">ID 4</th>
            <th
              style="text-align: center; width: 6%"
              v-if="packaging_level != 1"
            >
              SN Prefix (static)
            </th>
            <th
              style="text-align: center; width: 5%"
              v-if="packaging_level != 1"
            >
              SN Length (dynamic)
            </th>
            <th
              style="text-align: center; width: 12%"
              v-if="packaging_level != 1"
            >
              Generate Type
            </th>
            <th
              style="text-align: center; width: 12%"
              v-if="packaging_level != 1"
            >
              Charset
            </th>
            <th
              v-if="packaging_level != 1"
              style="text-align: center; width: 18%"
            >
              Layout
            </th>
            <th
              style="text-align: center; width: 53%"
              v-if="packaging_level == 1"
            ></th>
          </thead>
          <tbody :v-if="total_pid > 0" v-for="index in total_pid" :key="index">
            <tr>
              <td>
                {{ title[index - 1] }}
              </td>
              <td>
                <br />
                <CSelect
                  block
                  size="sm"
                  :disabled="readonly"
                  :options="index % 2 == 0 ? only_sscc : list_epc_type"
                  @change="handleChangePid(index - 1)"
                  :value.sync="result[index - 1].epc_type"
                  placeholder="--Select--"
                  :is-valid="!error[index - 1].epc_type"
                >
                </CSelect>
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  v-c-tooltip="
                    'This ID1 will be in the first order of the Epc Hr arrangement which will be generated by mertrack, the character length is only 1 digit number.'
                  "
                  :disabled="readonly"
                  v-model="result[index - 1].id1"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: digit_max[index - 1].id1,
                      name: 'id1',
                      type: 'number',
                    })
                  "
                  :is-valid="!error[index - 1].id1"
                />
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  v-c-tooltip="
                    'ID2 is filled with a company prefix with a minimum length of 6 digits and a maximum length of 9 digits.'
                  "
                  :disabled="readonly || packaging_level != 1"
                  v-model="result[index - 1].id2"
                  @keyup="handleChangePid(index - 1)"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: digit_max[index - 1].id2,
                      name: 'id2',
                      type: 'number',
                    })
                  "
                  :is-valid="!error[index - 1].id2"
                />
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  v-c-tooltip="
                    'ID3 is filled with the remaining 13 digits if ID1, ID2 and ID3 are added together.'
                  "
                  :disabled="
                    readonly ||
                    digit_max[index - 1].id3 == 0 ||
                    packaging_level != 1
                  "
                  :readonly="result[index - 1].epc_type === 'sscc'"
                  v-model="result[index - 1].id3"
                  @keyup="handleChangePid(index - 1)"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: digit_max[index - 1].id3,
                      name: 'id3',
                      type: 'number',
                    })
                  "
                  :is-valid="!error[index - 1].id3"
                />
              </td>
              <td>
                <br />
                <CInput
                  size="sm"
                  :disabled="readonly"
                  readonly
                  v-model="result[index - 1].id4"
                  @keyup="handleChangePid(index - 1)"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: digit_max[index - 1].id4,
                      name: 'id4',
                      type: 'number',
                    })
                  "
                  :is-valid="result[index - 1].id4 && !error[index - 1].id4"
                />
              </td>
              <td v-if="packaging_level != 1">
                <br />
                <CInput
                  size="sm"
                  :disabled="readonly"
                  v-model="result[index - 1].sn_prefix"
                  @keyup="handleChangePid(index - 1)"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: digit_max[index - 1].sn_prefix,
                      name: 'sn_prefix',
                      type:
                        result[index - 1].sn_charset == 'alphanumeric'
                          ? 'string'
                          : 'number',
                    })
                  "
                  :is-valid="!error[index - 1].sn_prefix"
                />
              </td>
              <td v-if="packaging_level != 1">
                <br />
                <CInput
                  size="sm"
                  :disabled="readonly"
                  :readonly="result[index - 1].epc_type === 'sscc'"
                  v-model="result[index - 1].generated_sn_len"
                  @keyup="handleChangePid(index - 1)"
                  @keypress="
                    validateCharSet({
                      event: $event,
                      num: index - 1,
                      max: 2,
                      name: 'generated_sn_len',
                      type: 'number',
                    })
                  "
                  :is-valid="!error[index - 1].generated_sn_len"
                />
              </td>
              <td v-if="packaging_level != 1">
                <br />
                <CSelect
                  size="sm"
                  :disabled="readonly"
                  :value.sync="result[index - 1].sn_generate_type"
                  @change="handleChangePid(index - 1)"
                  :options="list_generate_type"
                  placeholder="--Select--"
                  :is-valid="!error[index - 1].sn_generate_type"
                />
              </td>
              <td v-if="packaging_level != 1">
                <br />
                <CSelect
                  size="sm"
                  :disabled="result[index - 1].epc_type === 'sscc' || readonly"
                  @change="handleChangePid(index - 1)"
                  :value.sync="result[index - 1].sn_charset"
                  :options="list_charset"
                  placeholder="--Select--"
                  :is-valid="!error[index - 1].sn_charset"
                />
              </td>
              <td v-if="packaging_level != 1">
                <br />
                <CSelect
                  size="sm"
                  @change="handleChangePid(index - 1)"
                  :value.sync="result[index - 1].conf_layout_id"
                  :options="list_layout"
                  placeholder="-"
                  :is-valid="!error[index - 1].conf_layout_id"
                />
              </td>
            </tr>
          </tbody>
        </table>
      </template>
    </CCol>
  </CRow>
</template>

<script>
import { getConfLayout } from "../../resource/ConfLayout";
export default {
  name: "MasterPid",
  props: {
    item: Object,
    packaging_level: Number,
    default_data: Array,
    readonly: Boolean,
    ref_data: Object,
  },
  beforeMount() {
    let have_pid = false;
    var idx = 0;
    if (this.packaging_level == 1) {
      this.total_pid = 1;
      this.result.splice(1, 1);
      this.list_epc_type = this.only_sgtin;
      this.handleChangePid(0);
    }
    if (Object.keys(this.item).length > 5) {
      idx = 0;
      this.item.mst_pid.map((val, index) => {
        if (val.packaging_level == this.packaging_level) {
          have_pid = true;
          this.result[idx] = val;
          this.handleChangePid(idx);
          idx += 1;
        }
      });
      if (this.result.length == 2 && this.result[1].flag_full == 1) {
        this.swapPositions(this.result, 0, 1);
      }
    }
    if (!have_pid) {
      idx = 0;
      for (const it of this.result) {
        this.item.mst_pid.push(it);
        this.handleChangePid(idx);
        idx += 1;
      }
    }
  },
  watch: {
    item: {
      handler(n, o) {
        let index = 0;
        let pid_level_1 = {};
        let have_error = false;
        for (const pid of this.item.mst_pid) {
          if (pid.packaging_level == 1) {
            pid_level_1 = pid;
          }
        }
        for (const it of this.result) {
          if (this.packaging_level !== 1) {
            this.result[index].id2 = pid_level_1.id2;
            if (it.epc_type == "sgtin") {
              this.result[index].id3 = pid_level_1.id3;
            }
          }
          this.handleChangePid(index);
          for (var key in this.error[index]) {
            if (
              this.packaging_level === 1 &&
              (key === "generated_sn_len" ||
                key === "sn_charset" ||
                key === "sn_generate_type" ||
                key === "conf_layout_id")
            ) {
              have_error = false;
            } else if (this.error[index][key]) {
              have_error = true;
            }
          }
          if (have_error) {
            this.result[index].error = true;
          } else {
            this.result[index].error = false;
          }
          index += 1;
        }
        this.$emit("handleResultPid", this.result);
      },
      deep: true,
    },
  },
  mounted() {
    this.loadLayout();
  },
  data() {
    return {
      total_pid: 2,
      title: ["Full", "Partial"],
      digit_sscc: 17, // 1 digit adalah check digit
      digit_sgtin: 13, // 1 digit adalah check digit
      max_digit_ssscc: null,
      max_digit_sgtin: 20,
      digit_max: [this.initial_max(), this.initial_max()],
      max_sn_pref: 2,
      product: {},
      result: [this.initial_value(0), this.initial_value(1)],
      list_charset: [
        { value: "alphanumeric", label: "Alphanumeric" },
        { value: "numeric", label: "Numeric" },
      ],
      list_layout: [],
      list_epc_type: [
        { value: "sscc", label: "SSCC" },
        { value: "sgtin", label: "SGTIN" },
      ],
      only_sscc: [{ value: "sscc", label: "SSCC" }],
      only_sgtin: [{ value: "sgtin", label: "SGTIN" }],
      list_generate_type: [
        { value: "random", label: "Random" },
        { value: "sequential", label: "Sequential" },
      ],
      error: [this.initial_error(), this.initial_error()],
      have_error: [false, false],
      initial_save: false,
    };
  },
  computed: {},
  methods: {
    async loadLayout() {
      let _res = await getConfLayout({ status: "Active" });
      if (_res) {
        this.list_layout = [];
        for (const it of _res.data) {
          it.value = it.id;
          it.label = it.name;
          this.list_layout.push(it);
        }
      }
    },
    initial_max(num) {
      let it = {
        id1: 1,
        id2: 8,
        id3: 2,
        id4: 0,
        sn_prefix: num || 2,
      };
      return it;
    },
    initial_error() {
      let it = {
        epc_type: false,
        generated_sn_len: false,
        sn_charset: false,
        sn_generate_type: false,
        id1: false,
        id2: false,
        conf_layout_id: false,
      };
      return it;
    },
    initial_value(num) {
      let it = {
        product_id: this.item.product_id ?? null,
        packaging_level: this.packaging_level ?? null,
        flag_full: num ?? 1,
        flag_serial: this.item.product_type == "1" ? 0 : 1,
        epc_type: null,
        id1: null,
        id2: null,
        id3: null,
        id4: null,
        sn_charset: null,
        sn_generate_type: null,
        sn_prefix: null,
        generated_sn_len: null,
        conf_layout_id: null,
        error: true,
      };
      return it;
    },
    swapPositions(array, a, b) {
      [array[a], array[b]] = [array[b], array[a]];
    },
    validateNumber: function ({ event, data, max }) {
      event = event ? event : window.event;
      var charCode = event.which ? event.which : event.keyCode;
      if (data && data.toString().length > max - 1) {
        event.preventDefault();
      } else if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        event.preventDefault();
      } else {
        return true;
      }
    },

    validateCharSet: function ({ event, num, name, max, type }) {
      let data = this.result[num][name];
      event = event ? event : window.event;
      var charCode = event.which ? event.which : event.keyCode;
      if (data && data.toString().length > max - 1) {
        event.preventDefault();
      } else if (!type || type == "number") {
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
          event.preventDefault();
        } else {
          return true;
        }
      } else {
        return true;
      }
    },
    isNum(num) {
      const pattern = /^\d+$/;
      if (pattern.test(num)) return true;
      else return false;
    },
    handleChangePid(num) {
      this.error[num] = this.initial_error();
      // this.result[num].error = false;
      let id1 = this.result[num].id1 ?? "";
      let id2 = this.result[num].id2 ?? "";
      let id3 = this.result[num].id3 ?? "";
      let id4 = this.result[num].id4 ?? "";
      let sn_prefix = this.result[num].sn_prefix ?? "";
      let epc = this.result[num].epc_type;
      let sn_generate_type = this.result[num].sn_generate_type;
      let generated_sn_len = this.result[num].generated_sn_len;
      let sn_charset = this.result[num].sn_charset;
      let conf_layout_id = this.result[num].conf_layout_id;
      // Check id1 and id2 and generate type
      if (!id1 || !this.isNum(id1)) {
        this.error[num].id1 = true;
      }
      if (id2.length < 6 || id2.length > 9 || !this.isNum(id2)) {
        this.error[num].id2 = true;
      }
      if (id3 && !this.isNum(id3)) {
        this.error[num].id3 = true;
      }
      if (id4 && !this.isNum(id4)) {
        this.error[num].id4 = true;
      }
      if (sn_prefix && !this.isNum(sn_prefix)) {
        this.error[num].sn_prefix = true;
      }
      if (!sn_generate_type && this.packaging_level != 1) {
        this.error[num].sn_generate_type = true;
      }
      if (
        (!generated_sn_len && this.packaging_level != 1) ||
        !this.isNum(generated_sn_len)
      ) {
        this.error[num].generated_sn_len = true;
      }
      if (!sn_charset && this.packaging_level != 1) {
        this.error[num].sn_charset = true;
      }
      if (!conf_layout_id && this.packaging_level != 1) {
        this.error[num].conf_layout_id = true;
      }
      // Check epc type
      if (epc === "sscc") {
        this.checkSSCC(num);
      } else if (epc === "sgtin") {
        this.checkSGTIN(num);
      } else {
        this.error[num].epc_type = true;
      }
    },
    checkSSCC(num) {
      let id1 = this.result[num].id1 ?? "";
      let id2 = this.result[num].id2 ?? "";
      this.result[num].id3 = "";
      let sn_prefix = this.result[num].sn_prefix ?? "";
      let concat = ("" + id1 + id2 + sn_prefix).length;
      this.result[num].sn_charset = "numeric";
      this.result[num].generated_sn_len = this.digit_sscc - concat;
      // Check Error Total digit id1,id2,id3
      return;
    },
    checkSGTIN(num) {
      let id1 = this.result[num].id1 ?? "";
      let id2 = this.result[num].id2 ?? "";
      let id3 = this.result[num].id3 ?? "";
      let max_all = this.digit_sgtin.valueOf();
      let concat = ("" + id1 + id2 + id3).length;
      // Check Error Total digit id1,id2,id3
      if (!id1) {
        this.error[num].id1 = true;
      } else if (concat != max_all) {
        this.error[num].id2 = true;
        this.error[num].id3 = true;
      }
      // Check Error maximum length id1,id2
      let concat_1 = ("" + id1 + id2).length;
      let concat_2 = ("" + id1 + id3).length;
      if (concat_1 >= this.digit_sgtin) {
        this.result[num].id3 = "";
        this.digit_max[num].id3 = 0;
      } else {
        this.digit_max[num].id2 = this.digit_sgtin - concat_2;
        this.digit_max[num].id3 = this.digit_sgtin - concat_1;
      }
      // Check Error max sn dan prefix
      let sn_prefix = this.result[num].sn_prefix ?? "";
      let generated_sn_len = this.result[num].generated_sn_len ?? "";
      let concat_sn = ("" + sn_prefix).length;
      let len_sn = parseInt(this.result[num].generated_sn_len);
      if (!generated_sn_len) {
        this.error[num].generated_sn_len = true;
      } else if (concat_sn + len_sn > this.max_digit_sgtin) {
        this.result[num].generated_sn_len = this.max_digit_sgtin - concat_sn;
      }
      // Check Error Generate Type dan charset
      if (!this.result[num].sn_generate_type) {
        this.error[num].sn_generate_type = true;
      }
      if (!this.result[num].sn_charset) {
        this.error[num].sn_charset = true;
      }
      return;
    },

    validationData(num) {
      this.result[num].error = false;
      let is_error = false;
      for (var key in this.error[num]) {
        if (!this.result[`${num}`][key]) {
          this.error[num][key] = true;
          is_error = true;
        } else if (
          key == "id2" &&
          this.result[`${num}`][key].toString().length <= 5
        ) {
          this.error[num][key] = true;
          is_error = true;
        } else if (
          key == "generated_sn_len" &&
          this.result[`${num}`][key] <= 0
        ) {
          this.error[num][key] = true;
          is_error = true;
        }
      }
      if (is_error) {
        this.result[num].error = true;
      }
      this.$emit("handleResultPid", this.result);
    },
  },
};
</script>
<style>
.is-valid .custom-select-icon,
.is-invalid .custom-select-icon {
  width: 1px;
}
</style>
