export function coutryCode() {
  const countryData = [
    { value: "", label: "- Country -" },
    { value: "+62", label: "Indonesia" },
    { label: "Afghanistan", value: "+93", kode: "AF" },
    { label: "Albania", value: "+355", kode: "AL" },
    { label: "Algeria", value: "+213", kode: "DZ" },
    { label: "AmericanSamoa", value: "+1 684", kode: "AS" },
    { label: "Andorra", value: "+376", kode: "AD" },
    { label: "Angola", value: "+244", kode: "AO" },
    { label: "Anguilla", value: "+1 264", kode: "AI" },
    { label: "Antarctica", value: "+672", kode: "AQ" },
    { label: "Antigua and Barbuda", value: "+1268", kode: "AG" },
    { label: "Argentina", value: "+54", kode: "AR" },
    { label: "Armenia", value: "+374", kode: "AM" },
    { label: "Aruba", value: "+297", kode: "AW" },
    { label: "Australia", value: "+61", kode: "AU" },
    { label: "Austria", value: "+43", kode: "AT" },
    { label: "Azerbaijan", value: "+994", kode: "AZ" },
    { label: "Bahamas", value: "+1 242", kode: "BS" },
    { label: "Bahrain", value: "+973", kode: "BH" },
    { label: "Bangladesh", value: "+880", kode: "BD" },
    { label: "Barbados", value: "+1 246", kode: "BB" },
    { label: "Belarus", value: "+375", kode: "BY" },
    { label: "Belgium", value: "+32", kode: "BE" },
    { label: "Belize", value: "+501", kode: "BZ" },
    { label: "Benin", value: "+229", kode: "BJ" },
    { label: "Bermuda", value: "+1 441", kode: "BM" },
    { label: "Bhutan", value: "+975", kode: "BT" },
    { label: "Bolivia, Plurinational State of", value: "+591", kode: "BO" },
    { label: "Bosnia and Herzegovina", value: "+387", kode: "BA" },
    { label: "Botswana", value: "+267", kode: "BW" },
    { label: "Brazil", value: "+55", kode: "BR" },
    { label: "British Indian Ocean Territory", value: "+246", kode: "IO" },
    { label: "Brunei Darussalam", value: "+673", kode: "BN" },
    { label: "Bulgaria", value: "+359", kode: "BG" },
    { label: "Burkina Faso", value: "+226", kode: "BF" },
    { label: "Burundi", value: "+257", kode: "BI" },
    { label: "Cambodia", value: "+855", kode: "KH" },
    { label: "Cameroon", value: "+237", kode: "CM" },
    { label: "Canada", value: "+1", kode: "CA" },
    { label: "Cape Verde", value: "+238", kode: "CV" },
    { label: "Cayman Islands", value: "+ 345", kode: "KY" },
    { label: "Central African Republic", value: "+236", kode: "CF" },
    { label: "Chad", value: "+235", kode: "TD" },
    { label: "Chile", value: "+56", kode: "CL" },
    { label: "China", value: "+86", kode: "CN" },
    { label: "Christmas Island", value: "+61", kode: "CX" },
    { label: "Cocos (Keeling) Islands", value: "+61", kode: "CC" },
    { label: "Colombia", value: "+57", kode: "CO" },
    { label: "Comoros", value: "+269", kode: "KM" },
    { label: "Congo", value: "+242", kode: "CG" },
    {
      label: "Congo, The Democratic Republic of the",
      value: "+243",
      kode: "CD",
    },
    { label: "Cook Islands", value: "+682", kode: "CK" },
    { label: "Costa Rica", value: "+506", kode: "CR" },
    { label: "Cote d'Ivoire", value: "+225", kode: "CI" },
    { label: "Croatia", value: "+385", kode: "HR" },
    { label: "Cuba", value: "+53", kode: "CU" },
    { label: "Cyprus", value: "+537", kode: "CY" },
    { label: "Czech Republic", value: "+420", kode: "CZ" },
    { label: "Denmark", value: "+45", kode: "DK" },
    { label: "Djibouti", value: "+253", kode: "DJ" },
    { label: "Dominica", value: "+1 767", kode: "DM" },
    { label: "Dominican Republic", value: "+1 849", kode: "DO" },
    { label: "Ecuador", value: "+593", kode: "EC" },
    { label: "Egypt", value: "+20", kode: "EG" },
    { label: "El Salvador", value: "+503", kode: "SV" },
    { label: "Equatorial Guinea", value: "+240", kode: "GQ" },
    { label: "Eritrea", value: "+291", kode: "ER" },
    { label: "Estonia", value: "+372", kode: "EE" },
    { label: "Ethiopia", value: "+251", kode: "ET" },
    { label: "Falkland Islands (Malvinas)", value: "+500", kode: "FK" },
    { label: "Faroe Islands", value: "+298", kode: "FO" },
    { label: "Fiji", value: "+679", kode: "FJ" },
    { label: "Finland", value: "+358", kode: "FI" },
    { label: "France", value: "+33", kode: "FR" },
    { label: "French Guiana", value: "+594", kode: "GF" },
    { label: "French Polynesia", value: "+689", kode: "PF" },
    { label: "Gabon", value: "+241", kode: "GA" },
    { label: "Gambia", value: "+220", kode: "GM" },
    { label: "Georgia", value: "+995", kode: "GE" },
    { label: "Germany", value: "+49", kode: "DE" },
    { label: "Ghana", value: "+233", kode: "GH" },
    { label: "Gibraltar", value: "+350", kode: "GI" },
    { label: "Greece", value: "+30", kode: "GR" },
    { label: "Greenland", value: "+299", kode: "GL" },
    { label: "Grenada", value: "+1 473", kode: "GD" },
    { label: "Guadeloupe", value: "+590", kode: "GP" },
    { label: "Guam", value: "+1 671", kode: "GU" },
    { label: "Guatemala", value: "+502", kode: "GT" },
    { label: "Guernsey", value: "+44", kode: "GG" },
    { label: "Guinea", value: "+224", kode: "GN" },
    { label: "Guinea-Bissau", value: "+245", kode: "GW" },
    { label: "Guyana", value: "+595", kode: "GY" },
    { label: "Haiti", value: "+509", kode: "HT" },
    { label: "Holy See (Vatican City State)", value: "+379", kode: "VA" },
    { label: "Honduras", value: "+504", kode: "HN" },
    { label: "Hong Kong", value: "+852", kode: "HK" },
    { label: "Hungary", value: "+36", kode: "HU" },
    { label: "Iceland", value: "+354", kode: "IS" },
    { label: "India", value: "+91", kode: "IN" },
    { label: "Iran, Islamic Republic of", value: "+98", kode: "IR" },
    { label: "Iraq", value: "+964", kode: "IQ" },
    { label: "Ireland", value: "+353", kode: "IE" },
    { label: "Isle of Man", value: "+44", kode: "IM" },
    { label: "Israel", value: "+972", kode: "IL" },
    { label: "Italy", value: "+39", kode: "IT" },
    { label: "Jamaica", value: "+1 876", kode: "JM" },
    { label: "Japan", value: "+81", kode: "JP" },
    { label: "Jersey", value: "+44", kode: "JE" },
    { label: "Jordan", value: "+962", kode: "JO" },
    { label: "Kazakhstan", value: "+7 7", kode: "KZ" },
    { label: "Kenya", value: "+254", kode: "KE" },
    { label: "Kiribati", value: "+686", kode: "KI" },
    {
      label: "Korea, Democratic People's Republic of",
      value: "+850",
      kode: "KP",
    },
    { label: "Korea, Republic of", value: "+82", kode: "KR" },
    { label: "Kuwait", value: "+965", kode: "KW" },
    { label: "Kyrgyzstan", value: "+996", kode: "KG" },
    {
      label: "Lao People's Democratic Republic",
      value: "+856",
      kode: "LA",
    },
    { label: "Latvia", value: "+371", kode: "LV" },
    { label: "Lebanon", value: "+961", kode: "LB" },
    { label: "Lesotho", value: "+266", kode: "LS" },
    { label: "Liberia", value: "+231", kode: "LR" },
    { label: "Libyan Arab Jamahiriya", value: "+218", kode: "LY" },
    { label: "Liechtenstein", value: "+423", kode: "LI" },
    { label: "Lithuania", value: "+370", kode: "LT" },
    { label: "Luxembourg", value: "+352", kode: "LU" },
    { label: "Macao", value: "+853", kode: "MO" },
    {
      label: "Macedonia, The Former Yugoslav Republic of",
      value: "+389",
      kode: "MK",
    },
    { label: "Madagascar", value: "+261", kode: "MG" },
    { label: "Malawi", value: "+265", kode: "MW" },
    { label: "Malaysia", value: "+60", kode: "MY" },
    { label: "Maldives", value: "+960", kode: "MV" },
    { label: "Mali", value: "+223", kode: "ML" },
    { label: "Malta", value: "+356", kode: "MT" },
    { label: "Marshall Islands", value: "+692", kode: "MH" },
    { label: "Martinique", value: "+596", kode: "MQ" },
    { label: "Mauritania", value: "+222", kode: "MR" },
    { label: "Mauritius", value: "+230", kode: "MU" },
    { label: "Mayotte", value: "+262", kode: "YT" },
    { label: "Mexico", value: "+52", kode: "MX" },
    { label: "Micronesia, Federated States of", value: "+691", kode: "FM" },
    { label: "Moldova, Republic of", value: "+373", kode: "MD" },
    { label: "Monaco", value: "+377", kode: "MC" },
    { label: "Mongolia", value: "+976", kode: "MN" },
    { label: "Montenegro", value: "+382", kode: "ME" },
    { label: "Montserrat", value: "+1664", kode: "MS" },
    { label: "Morocco", value: "+212", kode: "MA" },
    { label: "Mozambique", value: "+258", kode: "MZ" },
    { label: "Myanmar", value: "+95", kode: "MM" },
    { label: "Namibia", value: "+264", kode: "NA" },
    { label: "Nauru", value: "+674", kode: "NR" },
    { label: "Nepal", value: "+977", kode: "NP" },
    { label: "Netherlands", value: "+31", kode: "NL" },
    { label: "Netherlands Antilles", value: "+599", kode: "AN" },
    { label: "New Caledonia", value: "+687", kode: "NC" },
    { label: "New Zealand", value: "+64", kode: "NZ" },
    { label: "Nicaragua", value: "+505", kode: "NI" },
    { label: "Niger", value: "+227", kode: "NE" },
    { label: "Nigeria", value: "+234", kode: "NG" },
    { label: "Niue", value: "+683", kode: "NU" },
    { label: "Northern Mariana Islands", value: "+1 670", kode: "MP" },
    { label: "Norway", value: "+47", kode: "NO" },
    { label: "Oman", value: "+968", kode: "OM" },
    { label: "Pakistan", value: "+92", kode: "PK" },
    { label: "Palau", value: "+680", kode: "PW" },
    { label: "Palestinian Territory, Occupied", value: "+970", kode: "PS" },
    { label: "Panama", value: "+507", kode: "PA" },
    { label: "Papua New Guinea", value: "+675", kode: "PG" },
    { label: "Paraguay", value: "+595", kode: "PY" },
    { label: "Peru", value: "+51", kode: "PE" },
    { label: "Philippines", value: "+63", kode: "PH" },
    { label: "Pitcairn", value: "+872", kode: "PN" },
    { label: "Poland", value: "+48", kode: "PL" },
    { label: "Portugal", value: "+351", kode: "PT" },
    { label: "Puerto Rico", value: "+1 939", kode: "PR" },
    { label: "Qatar", value: "+974", kode: "QA" },
    { label: "Romania", value: "+40", kode: "RO" },
    { label: "Russia", value: "+7", kode: "RU" },
    { label: "Rwanda", value: "+250", kode: "RW" },
    { label: "Réunion", value: "+262", kode: "RE" },
    { label: "Saint Barthélemy", value: "+590", kode: "BL" },
    {
      label: "Saint Helena, Ascension and Tristan Da Cunha",
      value: "+290",
      kode: "SH",
    },
    { label: "Saint Kitts and Nevis", value: "+1 869", kode: "KN" },
    { label: "Saint Lucia", value: "+1 758", kode: "LC" },
    { label: "Saint Martin", value: "+590", kode: "MF" },
    { label: "Saint Pierre and Miquelon", value: "+508", kode: "PM" },
    {
      label: "Saint Vincent and the Grenadines",
      value: "+1 784",
      kode: "VC",
    },
    { label: "Samoa", value: "+685", kode: "WS" },
    { label: "San Marino", value: "+378", kode: "SM" },
    { label: "Sao Tome and Principe", value: "+239", kode: "ST" },
    { label: "Saudi Arabia", value: "+966", kode: "SA" },
    { label: "Senegal", value: "+221", kode: "SN" },
    { label: "Serbia", value: "+381", kode: "RS" },
    { label: "Seychelles", value: "+248", kode: "SC" },
    { label: "Sierra Leone", value: "+232", kode: "SL" },
    { label: "Singapore", value: "+65", kode: "SG" },
    { label: "Slovakia", value: "+421", kode: "SK" },
    { label: "Slovenia", value: "+386", kode: "SI" },
    { label: "Solomon Islands", value: "+677", kode: "SB" },
    { label: "Somalia", value: "+252", kode: "SO" },
    { label: "South Africa", value: "+27", kode: "ZA" },
    {
      label: "South Georgia and the South Sandwich Islands",
      value: "+500",
      kode: "GS",
    },
    { label: "Spain", value: "+34", kode: "ES" },
    { label: "Sri Lanka", value: "+94", kode: "LK" },
    { label: "Sudan", value: "+249", kode: "SD" },
    { label: "Suriname", value: "+597", kode: "SR" },
    { label: "Svalbard and Jan Mayen", value: "+47", kode: "SJ" },
    { label: "Swaziland", value: "+268", kode: "SZ" },
    { label: "Sweden", value: "+46", kode: "SE" },
    { label: "Switzerland", value: "+41", kode: "CH" },
    { label: "Syrian Arab Republic", value: "+963", kode: "SY" },
    { label: "Taiwan, Province of China", value: "+886", kode: "TW" },
    { label: "Tajikistan", value: "+992", kode: "TJ" },
    { label: "Tanzania, United Republic of", value: "+255", kode: "TZ" },
    { label: "Thailand", value: "+66", kode: "TH" },
    { label: "Timor-Leste", value: "+670", kode: "TL" },
    { label: "Togo", value: "+228", kode: "TG" },
    { label: "Tokelau", value: "+690", kode: "TK" },
    { label: "Tonga", value: "+676", kode: "TO" },
    { label: "Trinidad and Tobago", value: "+1 868", kode: "TT" },
    { label: "Tunisia", value: "+216", kode: "TN" },
    { label: "Turkey", value: "+90", kode: "TR" },
    { label: "Turkmenistan", value: "+993", kode: "TM" },
    { label: "Turks and Caicos Islands", value: "+1 649", kode: "TC" },
    { label: "Tuvalu", value: "+688", kode: "TV" },
    { label: "Uganda", value: "+256", kode: "UG" },
    { label: "Ukraine", value: "+380", kode: "UA" },
    { label: "United Arab Emirates", value: "+971", kode: "AE" },
    { label: "United Kingdom", value: "+44", kode: "GB" },
    { label: "United States", value: "+1", kode: "US" },
    { label: "Uruguay", value: "+598", kode: "UY" },
    { label: "Uzbekistan", value: "+998", kode: "UZ" },
    { label: "Vanuatu", value: "+678", kode: "VU" },
    {
      label: "Venezuela, Bolivarian Republic of",
      value: "+58",
      kode: "VE",
    },
    { label: "Viet Nam", value: "+84", kode: "VN" },
    { label: "Virgin Islands, British", value: "+1 284", kode: "VG" },
    { label: "Virgin Islands, U.S.", value: "+1 340", kode: "VI" },
    { label: "Wallis and Futuna", value: "+681", kode: "WF" },
    { label: "Yemen", value: "+967", kode: "YE" },
    { label: "Zambia", value: "+260", kode: "ZM" },
    { label: "Zimbabwe", value: "+263", kode: "ZW" },
    { label: "Åland Islands", value: "+358", kode: "AX" },
  ];
  return countryData;
}
