const generalMenu = [
  {
    _name: "CSidebarNav",
    _children: [
      {
        _name: "CSidebarNavItem",
        name: "Dashboard",
        to: "/dashboard",
        link: "/dashboard",
        icon: "",
      },
      {
        _name: "CSidebarNavDropdown",
        name: "Master",
        route: "/master",
        link: "",
        icon: "",
        items: [
          {
            _name: "CSidebarNavItem",
            name: "Customer",
            to: "/master/customer",
            link: "/master/customer",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Supplier",
            to: "/master/supplier",
            link: "/master/supplier",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Product",
            to: "/master/product",
            link: "/master/product",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Product Category",
            to: "/master/product-category",
            link: "/master/product-category",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Warehouse",
            to: "/master/warehouse",
            link: "/master/warehouse",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Packaging",
            to: "/master/packaging",
            link: "/master/packaging",
            icon: "",
          },
        ],
      },
      {
        _name: "CSidebarNavDropdown",
        name: "Transaction",
        route: "/transaction",
        link: "",
        icon: "",
        items: [
          {
            _name: "CSidebarNavItem",
            name: "Upload Data XML/Manual",
            to: "/transaction/upload_xml",
            link: "/transaction/upload_xml",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Inbound",
            to: "/transaction/inbound",
            link: "/transaction/inbound",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Outbound",
            to: "/transaction/outbound",
            link: "/transaction/outbound",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Return",
            to: "/transaction/return",
            link: "/transaction/return",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Disposal",
            to: "/transaction/disposal",
            link: "/transaction/disposal",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Indirect Request",
            to: "/transaction/indirect_request",
            link: "/transaction/indirect_request",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Rework",
            to: "/transaction/rework",
            link: "/transaction/rework",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Aggregation",
            to: "/transaction/aggregation",
            link: "/transaction/aggregation",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Re-Aggregation",
            to: "/transaction/re-aggregation",
            link: "/transaction/re-aggregation",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Packing",
            to: "/transaction/packing",
            link: "/transaction/packing",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Unpacking",
            to: "/transaction/re-packing",
            link: "/transaction/re-packing",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Decommisioning",
            to: "/transaction/comm-decomm",
            link: "/transaction/comm-decomm",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "BPOM",
            to: "/transaction/bpom_reporting",
            link: "/transaction/bpom_reporting",
            icon: "",
          },
        ],
      },
      {
        _name: "CSidebarNavDropdown",
        name: "Setting",
        route: "/setting",
        link: "",
        icon: "",
        items: [
          {
            _name: "CSidebarNavItem",
            name: "Users",
            to: "/setting/user",
            link: "/setting/user",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Roles",
            to: "/setting/role",
            link: "/setting/role",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Department",
            to: "/setting/department",
            link: "/setting/department",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Section",
            to: "/setting/section",
            link: "/setting/section",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Workflow",
            to: "/setting/workflow",
            link: "/setting/workflow",
            icon: "",
          },
          {
            _name: "CSidebarNavItem",
            name: "Template Barcode",
            to: "/setting/template_barcode",
            link: "/setting/template_barcode",
            icon: "",
          },
        ],
      },
    ],
  },
];

const userMenu = [
  {
    _name: "CSidebarNav",
    _children: JSON.parse(localStorage.getItem("menu")),
  },
];

export default userMenu;
