export const GS1_application_identifiers = [
  //FIX_AI = [
  { ai: '00', type: 'SSCC', length: 18, alias: 'sscc', column: 'epc_key' },
  { ai: '01', type: 'GTIN', length: 14, alias: 'sgtin', column: 'epc_key' },
  { ai: '02', type: 'CONTENT', length: 14, alias: 'content', column: '' }, //GTIN CONTENT
  {
    ai: '17',
    type: 'EXPIRY_DATE',
    length: 6,
    alias: 'exp',
    column: 'expired_date',
  },

  //  DINAMIC_AI = [
  {
    ai: '10',
    type: 'BATCH',
    length: null,
    max_length: 20,
    alias: 'batch_no',
    column: 'batch_no',
  },
  {
    ai: '21',
    type: 'SERIAL',
    length: null,
    max_length: 20,
    alias: 'serial',
    column: 'serial',
  },
  {
    ai: '30',
    type: 'VAR_COUNT',
    length: null,
    max_length: 8,
    alias: null,
    column: 'gtin_sscc',
  },
  {
    ai: '37',
    type: 'COUNT',
    length: null,
    max_length: 8,
    alias: 'count',
    column: 'quantity',
  },
  {
    ai: '3100',
    type: 'WEIGHT',
    length: 6,
    max_length: null,
    alias: 'weight',
    column: 'weight',
  },
  {
    ai: '3101',
    type: 'WEIGHT',
    length: 6,
    max_length: null,
    alias: 'weight',
    column: 'weight',
  },
  {
    ai: '3102',
    type: 'WEIGHT',
    length: 6,
    max_length: null,
    alias: 'weight',
    column: 'weight',
  },
  {
    ai: '3103',
    type: 'WEIGHT',
    length: 6,
    max_length: null,
    alias: 'weight',
    column: 'weight',
  },
  {
    ai: '3104',
    type: 'WEIGHT',
    length: 6,
    max_length: null,
    alias: 'weight',
    column: 'weight',
  },
  {
    ai: '3105',
    type: 'WEIGHT',
    length: 6,
    max_length: null,
    alias: 'weight',
    column: 'weight',
  },
  // Di taruh dibawah karena jarang terpakai AI tersebut
  //FIX_AI = [
  {
    ai: '11',
    type: 'PROD_DATE',
    length: 6,
    alias: 'prod_date',
    column: 'mfg_date',
  },
  { ai: '12', type: 'DUE_DATE', length: 6, alias: 'due_date', column: '' },
  { ai: '13', type: 'PACK_DATE', length: 6, alias: 'pack_date', column: '' },
  {
    ai: '15',
    type: 'BEST_BEFORE',
    length: 6,
    alias: 'best_before',
    column: '',
  },
  { ai: '20', type: 'VARIANT', length: 2, alias: 'variant', column: '' },
  {
    ai: '410',
    type: 'SHIP_TO_LOC',
    length: 13,
    alias: 'ship_to_loc',
    column: '',
  },
  { ai: '411', type: 'BILL_TO', length: 13, alias: 'bill_to', column: '' },
  { ai: '412', type: 'PURCHASE_FROM', length: 13, alias: null, column: '' },
  { ai: '413', type: 'SHIP_FOR_LOC', length: 13, alias: null, column: '' },
  { ai: '414', type: 'LOC_NO', length: 13, alias: 'loc_no', column: '' },
  { ai: '415', type: 'PAY_TO', length: 13, alias: 'pay_to', column: '' },
  { ai: '422', type: 'ORIGIN', length: 3, alias: 'origin', column: '' },
  { ai: '424', type: 'COUNTRY_PROCESS', length: 3, alias: null, column: '' },
  {
    ai: '426',
    type: 'COUNTRY_FULL_PROCESS',
    length: 3,
    alias: null,
    column: '',
  },
  { ai: '7001', type: 'NSN', length: 13, alias: 'nsn', column: '' },
  {
    ai: '7003',
    type: 'EXPIRY_TIME',
    length: 10,
    alias: 'exp_time',
    column: '',
  },
  {
    ai: '8001',
    type: 'DIMENSIONS',
    length: 14,
    alias: 'dimensions',
    column: '',
  },
  { ai: '8005', type: 'PRICE_PER_UNIT', length: 6, alias: null, column: '' },
  { ai: '8017', type: 'GSRN_PROVIDER', length: 18, alias: null, column: '' },
  { ai: '8018', type: 'GSRN_RECIPIENT', length: 18, alias: null, column: '' },

  //  DINAMIC_AI = [
  {
    ai: '22',
    type: 'CPV',
    length: null,
    max_length: 20,
    alias: 'cpv',
    column: '',
  },
  {
    ai: '400',
    type: 'ORDER_NUMBER',
    length: null,
    max_length: 30,
    alias: null,
    column: '',
  },
  {
    ai: '401',
    type: 'GINC',
    length: null,
    max_length: 30,
    alias: 'ginc',
    column: '',
  },
  {
    ai: '403',
    type: 'ROUTE',
    length: null,
    max_length: 30,
    alias: 'route',
    column: '',
  },
  {
    ai: '420',
    type: 'SHIP_TO_POST',
    length: null,
    max_length: 20,
    alias: null,
    column: '',
  },
  {
    ai: '8004',
    type: 'GIAI',
    length: null,
    max_length: 30,
    alias: 'giai',
    column: '',
  },
  {
    ai: '8007',
    type: 'IBAN',
    length: null,
    max_length: 36,
    alias: 'iban',
    column: '',
  },
  {
    ai: '8013',
    type: 'GMN',
    length: null,
    max_length: 30,
    alias: 'gmn',
    column: '',
  },
  {
    ai: '8020',
    type: 'REF_NO',
    length: null,
    max_length: 25,
    alias: 'ref_no',
    column: '',
  },
  {
    ai: '8110',
    type: 'COUPON',
    length: null,
    max_length: 70,
    alias: 'coupon',
    column: '',
  },
  {
    ai: '90',
    type: 'INTERNAL',
    length: null,
    max_length: 16,
    alias: 'nie', //NIE UNTUK BPOM
    column: 'epc_key',
  },
  {
    ai: '91',
    type: 'INTERNAL',
    length: null,
    max_length: 50,
    alias: 'ns', //EPC KEY Khusus untuk nonserial
    column: 'epc_key',
  },
  // .... sampai AI 99 adalah internal
];
